apiVersion: apps/v1
kind: Deployment
metadata:
  name: sicheong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sicheong
  template:
    metadata:
      labels:
        app: sicheong
    spec:
      containers:
        - name: sicheong
          # Put the same base image path that your workflow will replace.
          # Using the env values from your workflow by default:
          image: asia-northeast3-docker.pkg.dev/sicheong-1/sicheong-docker-repo/sicheong:latest
          resources:
            limits:
              memory: "500Mi"
              cpu: "100m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
